{% set version = '0.4' %}
{% set sha256 = '06fc0874e1e27c91c862d40b24ee314b95e038275ce653a3dfd8eca00030a85f' %}

package:
  name: unumpy
  version: {{ version }}

source:
  fn: unumpy-{{ version }}.tar.gz
  url: https://github.com/Quansight-Labs/unumpy/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - python
  run:
    - python

build:
  noarch: python

test: {}

about:
  home: https://github.com/Quansight-Labs/unumpy
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Array interface object for Python with pluggable backends and a multiple-dispatch mechanism for defining down-stream functions'
  dev_url: https://github.com/Quansight-Labs/unumpy

extra:
  recipe-maintainers:
    - hameerabbasi
    - costrouc
